### ISSUE TITLE
Windows: Failed to find available port

### ISSUE THREAD

**Issue by jonobr1** [CharlesHolbrow/monode#5]
Hey there,

I've been using `monode` to great success on Mac. Thanks so much for writing and maintaining it! It's super easy to use. The other day I wanted to use it on my Windows 10 VR-Enabled PC. I have max patches running and communicating with my 128 grid, however when I try to run the sample `node ./out/lib/start.js` from a fresh `npm install monode` I get this error:

`Error: Failed to open main server: Error: Failed to find available port`

I checked the source and see that the port is hardcoded into `monome.js` so I just tried changing that number from `4545` to `4646` and `5555`, but still have the same error. Any ideas on what this could be?

Thanks for your time and awesome library!

**Comment by jonobr1** [comment]
Hmmm, so it seems I was able to fix the issue by replacing `0.0.0.0` as the host in `osc.js` as `localhost`. I'll submit a PR for this once I figure out a good way to figure out when to use one versus the other.

Thanks!

**Comment by CharlesHolbrow** [comment]
I believe 0.0.0.0 binds all network interfaces. Can you try using `127.0.0.1`, and see if that solves the problem? This is probably what it 'should' be. I'd be happy to accept a pull request.

**Comment by CharlesHolbrow** [comment]
@jonobr1  I just published monode 3.0.0 to npm. Can you check if this solves your issues?

**Comment by jonobr1** [comment]
Thanks for publishing a new version! 3.0.0 fixed it!
