### ISSUE TITLE
Multiple Monome's

### ISSUE THREAD

**Issue by jonobr1** [CharlesHolbrow/monode#6]
Can monode handle multiple Monomes? Whenever I plug in my Arc2 and then my 128 the server crashes with this error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:10200
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by CharlesHolbrow** [comment]
Curious. I definitely have used this with monome and arc at the same time. I'll try to reproduce this error when I'm back at my office on Monday. Thanks for opening the issue. If I can reproduce, it should be no trouble to solve. 

Can I ask what operating system and serialosc version you are using?

**Comment by jonobr1** [comment]
Thanks for the quick reply! Sorry, I'm traveling at the moment and won't be back in front of my computer with the equipment until Monday. However I am using [`serialosc v1.4`](https://github.com/monome/serialosc/releases/tag/v1.4) and I get this error on both Mac Yosemite and Windows 10. I'll keep you posted when I get back to my studio

**Comment by CharlesHolbrow** [comment]
I just published monode 3.0.0 to npm. Can you check if this solves your issues?

**Comment by CharlesHolbrow** [comment]
Hi @jonobr1, Bumping this  - can you check if version 3.00 solves your problem?

**Comment by jonobr1** [comment]
Thanks for publishing a new version! 3.0.0 fixed it!
